#lang:

root: "dsl"

environement:
    #SANE_DEFAULT_DEVICE: hpaio:/usb/HP_LaserJet_Professional_M1132_MFP?serial=000000000QH759WZPR1a
    SANE_DEFAULT_DEVICE: pixma:04A9173D_23E76F

scan_comments: |
    Repertoires principaux:
    * Documents importants/Identitié <personne>
    * Documents importants/Job <personne>
    * Documents importants/Assurances/<assurance>
    * Documents/<entreprise>/Courriers entrant
    * Documents/<entreprise>/Courriers sortant
    * Documents/<entreprise>/Garenties

    Nomoclature:
    Documents/<entreprise> - <personne> - <N° client>/<categorie>/<nom> - <data> - <N° page>

scan:
    Color:
        cmds:
        - scanc
        - crop
        - 2png
        - auto-rotate

    B&W:
        cmds:
        - scan
        - crop
        - cleanup
        - 2png
        - auto-rotate

ocr:
- ocr

postprocess:
- optipng

task:
    "Iptimise images":
        on: "*.png"
        cmds: 
        - optipng
    "Fix files names":
        cmds: 
        - fixextensions_case
        - fixextensions_jpeg
cmds:
    scan:
        cmd: "scanimage --format tiff --resolution 300 --mode Gray --gamma 1 -l 0 -t 0 -x 216.069 -y 297.011 > {out}"
        out_ext: tiff

    scanc:
        cmd: "scanimage --format tiff --resolution 300 --gamma 1 -l 0 -t 0 -x 216.069 -y 297.011i > {out}"
        out_ext: tiff

    crop: "convert {in} -crop `convert scan.tiff -crop 2502x3458+25+25 +repage -level 20%,80%,4 -virtual-pixel edge -blur 0x5 -fuzz 4% -trim -format '%[fx:w+50]x%[fx:h+50]+%[fx:page.x]+%[fx:page.y]' info:` +repage -normalize {out}"

    cleanup: "convert {in} -background white +matte -fuzz 10% -fill white -draw 'color 2540,3500 floodfill' -level 10%,80%,1 +matte {out}"

    2png:
        cmd: "convert {in} -format png {out}"
        out_ext: png

    auto-rotate: "convert test.png -rotate `tesseract -psm 0 -l fra test.png text 2>&1 | grep 'Orientation in degrees' | awk '{{print $4}}'` test2.png"

    ocr: "tesseract -l fra {in} {out}"

    optipng:
        cmd: "optipng -o7 {in}" 
        inplace: true
#        out: inplace

    fixextensions_case:
        type: remame
        from: "\.([a-zA-Z]+)$"
        format: lower

    fixextensions_jpeg:
        type: remame
        from: "\.jpg$"
        to: ".jpeg"
