#lang:

root_folder: "dsl/Documents"

environement:
    #SANE_DEFAULT_DEVICE: hpaio:/usb/HP_LaserJet_Professional_M1132_MFP?serial=000000000QH759WZPR1a
    SANE_DEFAULT_DEVICE: pixma:04A9173D_23E76F

scan_comments: |
    Repertoires principaux:
    * 0-Importants/Identitié <personne>
    * 0-Importants/Job <personne>
    * 0-Importants/Assurances/<assurance>
    * <entreprise>/Courriers entrant
    * <entreprise>/Courriers sortant
    * <entreprise>/Garenties

    Nomoclature:
    <entreprise> - <personne> - <N° client>/<categorie>/<nom> - <data> - <N° page>

scans:
  - name: Color
    cmds:
    - scanc
    - crop
    - 2png
    - auto-rotate

  - name: B&W
    default: true
    cmds:
    - scan
    - crop
    - cleanup
    - 2png
    - auto-rotate

to_txt:
  - extention: png
    cmds:
    - ocr

open_cmd: gnome-open

postprocess:
- optipng

task:
  - name: "Iptimise images"
    on: "*.png"
    cmds:
    - optipng
  - name: "Fix files names"
    cmds:
    - fixextensions_case
    - fixextensions_jpeg

cmds:
    scan:
        display: Scanning...
        cmd: "scanimage --format tiff --resolution 300 --mode Gray --gamma 1 -l 0 -t 0 -x 216.069 -y 297.011 > {out}"
        out_ext: tiff

    scanc:
        display: Scanning...
        cmd: "scanimage --format tiff --resolution 300 --gamma 1 -l 0 -t 0 -x 216.069 -y 297.011i > {out}"
        out_ext: tiff

    crop:
        display: Cropping.
        cmd: "convert {in} -crop `convert {in} -crop 2502x3458+25+25 +repage -level 20%,80%,4 -virtual-pixel edge -blur 0x5 -fuzz 4% -trim -format '%[fx:w+50]x%[fx:h+50]+%[fx:page.x]+%[fx:page.y]' info:` +repage -normalize {out}"

    #cleanup: "convert {in} -background white +matte -fuzz 10% -fill white -draw 'color 2540,3500 floodfill' -level 10%,80%,1 +matte -format tiff {out}"
    cleanup:
        display: Cleanup the file.
        cmd: "convert {in} -background white +matte -fuzz 10% -fill white -level 10%,80%,1 +matte -format tiff {out}"

    2png:
        display: Convert to PNG.
        cmd: "convert {in} -format png {out}"
        out_ext: png

    auto-rotate: 
        display: Automatic rotate.
        cmd: "convert {in} -rotate `tesseract -psm 0 -l fra {in} text 2>&1 | grep 'Orientation in degrees' | awk '{{print $4}}'` {out}"
        #cmd: "convert {in} -rotate `tesseract -psm 0 -l fra {in} text 2>&1 | grep 'Orientation in degrees' | awk '{{print $4}}' && echo 0` {out}"

    ocr:
        display: Reconnaissance optique des caractères.
        cmd: "tesseract -l fra {in} {out}"

    optipng:
        display: Optimisation de l'image.
        cmd: "optipng -o7 {in}"
        inplace: true
#        out: inplace

    fixextensions_case:
        display: Corrige la case des extentions.
        type: remame
        from: '\.([a-zA-Z]+)$'
        format: lower

    fixextensions_jpeg:
        display: Corrige ees extentions (.jpg -> .jpeg).
        type: remame
        from: '\.jpg$'
        to: '.jpeg'
