name: edocuments
version: git
summary: eDocuments
description: |
  eDocuments is a simple and productive personal documents library

grade: devel
confinement: devmode

icon: edocuments/ressources/edocuments.svg

apps:
  edocuments:
    command: bin/edocuments-gui
    desktop: usr/share/applications/edocuments.desktop
    plugs:
      - home
      - desktop
      - x11
      - wayland

parts:
  edocuments:
    plugin: python
    source: .
    stage-packages:
      - python3-pyqt5
    build-packages:
      - python3-pyqt5
      - pyqt5-dev-tools
    override-build: |
        make build
        snapcraftctl build
        cp edocuments/ressources/edocuments.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
        sed -i 's|yExec=.*|TryExec=/snap/bin/edocuments-gui|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/edocuments.desktop
        cp edocuments/ressources/edocuments.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/
    filesets:
      exclusion:
        - '*.ui'
        - '*.ts'
    prime:
      - "$exclusion"

