name: edocuments
version: git
summary: eDocuments
description: |
  eDocuments is a simple and productive personal documents library

grade: devel
confinement: devmode

icon: edocuments/ressources/edocuments.svg

apps:
  edocuments:
    command: bin/edocuments-gui
    desktop: edocuments/ressources/edocuments.desktop
    plugs:
      - home
      - desktop
      - x11
      - wayland

parts:
  edocuments:
    plugin: python
    source: .
    stage-packages:
      - python3-pyqt5
    build-packages:
      - python3-pyqt5
      - pyqt5-dev-tools
    override-build: |
        make build
        snapcraftctl build
        sed -i 's|yExec=.*|TryExec=/snap/bin/edocuments-gui|' edocuments/ressources/edocuments.desktop
    filesets:
      exclusion:
        - '-*.ui'
        - '-*.ts'
    prime:
      - "$exclusion"

