name: edocuments
version: git
summary: eDocuments
description: |
  eDocuments is a simple and productive personal documents library

grade: devel
confinement: classic

apps:
  edocuments:
    command: bin/edocuments-gui
    plugs:
      - home

parts:
  edocuments:
    plugin: python
    source: .
    stage-packages:
      - python3-pyqt5
    build-packages:
      - python3-pyqt5
      - pyqt5-dev-tools
    prepare: |
        make build

