name: edocuments
version: git
summary: eDocuments
description: |
  eDocuments is a simple and productive personal documents library

grade: devel
confinement: devmode

apps:
  edocuments:
    command: bin/edocuments-gui

parts:
  edocuments:
    plugin: python
    source: .
    stage-packages:
      - python3-pyqt5
    install: make build

